# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Group 1:
    - ç¾¤ç»„:
        - ç™¾ä¸‡çš„å¤§çª:
            href: https://qm.qq.com/q/F2b0lzn5wm
            description: ç‚¹å‡»å¡ç‰‡åŠ å…¥ç¾¤èŠã€ç™¾ä¸‡çš„å¤§çªã€‘
            icon: https://tc.z.wiki/autoupload/f/walXAp4Sav94xqwTB9S6BMoKOuqHx97M6G9c8juTwKuyl5f0KlZfm6UsKj-HyTuv/20250831/R3G9/512X512/baiwan.png
            widget:
                type: calendar
                firstDayInWeek: sunday # optional - defaults to monday
                view: monthly # optional - possible values monthly, agenda
                maxEvents: 10 # optional - defaults to 10
                showTime: true
                timezone: Asia/Shanghai

    - ğŸš€ç™¾ä¸‡å¸¸ç”¨:
        # - HomePage æ–‡æ¡£:
        #     href: https://gethomepage.dev/configs/
        #     description: HomePage å®˜æ–¹æ–‡æ¡£
        #     icon: https://imgbed.zhubaiwan.me/file/icons/1744906160197_homepage.png
        - å¤§çªé£ä¹¦æ–‡æ¡£:
            href: https://f0bhyxhlrjd.feishu.cn/wiki/E4JfwScP8i58Pbkzmqgcukjanhe
            description: ç™¾ä¸‡çš„å¤§çªç¾¤è§„ä¸åˆ†äº«æ–‡æ¡£
            icon: https://imgbed.zhubaiwan.me/file/icons/1744905989241_é£ä¹¦.png
        - LinuxDo:
            href: https://linux.do/
            description: ä¸€ä¸ªæ–°çš„ç†æƒ³å‹ç¤¾åŒº
            icon: https://tc-new.z.wiki/autoupload/f/walXAp4Sav94xqwTB9S6BMoKOuqHx97M6G9c8juTwKuyl5f0KlZfm6UsKj-HyTuv/20250807/3hp6/460X460/linuxdo.png
        - ç™¾ä¸‡ API:
            href: https://api.zhubaiwan.xyz/console/log
            description: ç™¾ä¸‡ API ç®¡ç†
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/newapi-color.png
        - Gmail:
            href: https://mail.google.com
            description: Gmail é‚®ç®±ç™»å½•
            icon: https://imgbed.zhubaiwan.me/file/icons/Gmail.png
        - Bilibili:
            href: https://www.bilibili.com/watchlater/list/
            description: B ç«™ç¨åè§‚çœ‹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/bilibili-color.png
        - å®‰ç†å·¥ä¸€å¡é€š:
            href: http://ecard.aust.edu.cn/epay/
            description: å®‰å¾½ç†å·¥å¤§å­¦æ ¡å›­å¡å……å€¼
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/master/icons/AUST.png
        - Gist:
            href: https://gist.github.com/mine
            description: GitHub Gist ä»£ç ç‰‡æ®µ
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/github.png
        - Zone.id:
            href: https://my.zone.id/subdomains/2gi4bfiq/url_forwarder/
            description: Zone.id å…è´¹åŸŸå
            icon: https://tc-new.z.wiki/autoupload/f/walXAp4Sav94xqwTB9S6BMoKOuqHx97M6G9c8juTwKuyl5f0KlZfm6UsKj-HyTuv/20250810/l4SL/200X200/zoneid.png
        # - Uni-API:
        #     href: https://huggingface.co/spaces/shiwan7788/leaderboard/settings
        #     description: ç»Ÿä¸€ç®¡ç†å¤§æ¨¡å‹ API
        #     icon: https://tc.z.wiki/autoupload/f/walXAp4Sav94xqwTB9S6BMoKOuqHx97M6G9c8juTwKuyl5f0KlZfm6UsKj-HyTuv/20250831/6FGX/1024X1024/uni-api.ico
        # - raw-access:
        #     href: https://github.com/ZhuBaiwan-oOZZXX/baiwan-raw
        #     description: é€šè¿‡ cloudflare è®¿é—®ç§äººä»“åº“
        #     icon: https://tc.z.wiki/autoupload/f/walXAp4Sav94xqwTB9S6BMoKOuqHx97M6G9c8juTwKuyl5f0KlZfm6UsKj-HyTuv/20250810/6WZb/200X200/raw.png
        # - OpenWebUI:
        #     href: https://chat.zhubaiwan.me/
        #     description: ç™¾ä¸‡çš„å…è´¹ AI ç½‘ç«™
        #     icon: https://imgbed.zhubaiwan.me/file/icons/1744788103769_openwebui.png

    - ğŸŒŸç™¾ä¸‡æ­å»º:
        - Sub-Store:
            href: https://sub.zhubaiwan.me/ 
            description: ç™¾ä¸‡çš„è®¢é˜…ç®¡ç†
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/cc63/ICON/main/Sub-Store.png
        - Converter:
            href: https://converter.zhubaiwan.me/
            description: Clash è®¢é˜…è½¬æ¢
            icon: https://cfimgbase.ggff.net/file/VPN.png
        - OuonnkiTV:
            href: https://tv.zhubaiwan.me/
            description: ç™¾ä¸‡çš„å…è´¹è§†é¢‘ç½‘ç«™
            icon: https://ouonnki.site/upload/logo.svg
        - Cloudflare-Proxy:
            href: https://proxy.zhubaiwan.me/
            description: URL ä»£ç†æœåŠ¡
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/master/icons/proxy.png
        - Model-Get: 
            href: https://model-get.zhubaiwan-oozzxx.me/
            description: ç”Ÿæˆ NewAPI æ¨¡å‹æ˜ å°„
            icon: https://img.icons8.com/?size=200&id=POBc2SrrhhnF&format=png
        - BW-model:
            href: https://bw-model.deno.dev/
            description: ç™¾ä¸‡ API æ¨¡å‹åˆ—è¡¨
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/master/icons/baiwan.png
        - ç™¾ä¸‡å›¾åºŠ (New):
            href: https://imgbed.zhubaiwan.me/
            description: ç™¾ä¸‡çš„å›¾åºŠ (æ–°)
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788095038_CloudFlare-ImgBed.png
        - ç™¾ä¸‡å›¾åºŠ (Outdated):
            href: https://pic.lovebw.ddns-ip.net/
            description: ç™¾ä¸‡çš„å›¾åºŠ (æ—§)
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788095038_CloudFlare-ImgBed.png
        # - OpenWebUI:
        #     href: https://chat.zhubaiwan.me/
        #     description: ç™¾ä¸‡çš„å…è´¹ AI ç½‘ç«™
        #     icon: https://imgbed.zhubaiwan.me/file/icons/1744788103769_openwebui.png
        # - Cloud Mail:
        #     href: https://lovebw.ggff.net/
        #     description: ç™¾ä¸‡çš„åŸŸåé‚®ç®±
        #     icon: https://tc.z.wiki/autoupload/f/walXAp4Sav94xqwTB9S6BMoKOuqHx97M6G9c8juTwKuyl5f0KlZfm6UsKj-HyTuv/20250810/svwP/200X200/email.png
        # - CloudPaste:
        #     href: https://cloudpaste.zhubaiwan.me/
        #     description: ç™¾ä¸‡çš„äº‘ç«¯å‰ªè´´æ¿
        #     icon: https://imgbed.zhubaiwan.me/file/icons/1745135835771_cloudpaste.png

- Group 2:
    - â˜ï¸å¼€å‘å·¥å…·/æœåŠ¡:
        - GitHub:
            href: https://github.com/
            description: GitHub ä»£ç æ‰˜ç®¡å¹³å°
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/github.png
        - Cloudflare:
            href: https://dash.cloudflare.com/
            description: åŸŸåæ‰˜ç®¡ä¸ CDN æœåŠ¡
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/cloudflare-color.png
        - Huggingface:
            href: https://huggingface.co/
            description: æœºå™¨å­¦ä¹ ä¸æ•°æ®é›†å¼€æºå¹³å°
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/huggingface-color.png
        - Render:
            href: https://dashboard.render.com/
            description: Render äº‘éƒ¨ç½²å¹³å°
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/master/icons/render.jpg
        - Aliyun:
            href: https://home.console.aliyun.com/home/dashboard/ProductAndService
            description: é˜¿é‡Œäº‘å®˜ç½‘
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/alibabacloud-color.png
        - Deno:
            href: https://dash.deno.com/
            description: Deno è¿è¡Œæ—¶éƒ¨ç½²å¹³å°
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788102406_deno.png
        - Vercel:
            href: https://vercel.com/
            description: Vercel å‰ç«¯éƒ¨ç½²å¹³å°
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/vercel.png
        - Zone.id:
            href: https://zone.id/
            description: Zone.id å…è´¹åŸŸå
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/master/icons/zoneid.png
        - Aiven:
            href: https://console.aiven.io/
            description: Aiven å…è´¹äº‘æ•°æ®åº“
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788102859_aiven.png
        - Koofr:
            href: https://app.koofr.net/
            description: Koofr äº‘å­˜å‚¨ä¸ WebDAV
            icon: https://imgbed.zhubaiwan.me/file/icons/1744795376085_koofr.png
        # - è…¾è®¯äº‘:
        #     href: https://cloud.tencent.com/
        #     description: è…¾è®¯äº‘äº‘è®¡ç®—æœåŠ¡å¹³å°
        #     icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/tencent-color.png
        # - Claw Cloud:
        #     href: https://console.run.claw.cloud/
        #     description: Claw Cloud åº”ç”¨éƒ¨ç½²å¹³å°
        #     icon: https://tc-new.z.wiki/autoupload/f/walXAp4Sav94xqwTB9S6BMoKOuqHx97M6G9c8juTwKuyl5f0KlZfm6UsKj-HyTuv/20250807/vojA/170X170/claw.webp
        # - Cloudns:
        #     href: https://www.cloudns.net/
        #     description: åŸŸåå’Œ DNS æœåŠ¡æä¾›å•†
        #     icon: https://imgbed.zhubaiwan.me/file/icons/1744788097192_cloudns.png

    - ğŸŒˆAI æœåŠ¡:
        - ChatGPT:
            href: https://chatgpt.com/
            description: OpenAI å¼€å‘çš„å¤§è¯­è¨€æ¨¡å‹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/openai.png
        - Gemini:
            href: https://gemini.google.com/
            description: Google å¼€å‘çš„åŸç”Ÿå¤šæ¨¡æ€å¤§è¯­è¨€æ¨¡å‹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/gemini-color.png
        - Google AI Studio:
            href: https://aistudio.google.com/
            description: ä½¿ç”¨ Gemini API
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/aistudio.png
        - Duck.ai:
            href: https://duckduckgo.com/?q=1&ia=chat&duckai=1
            description: DuckDuckGo å…è´¹ AI åŠ©æ‰‹
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/master/icons/duckduckgo.png
        - QwenChat:
            href: https://chat.qwen.ai/
            description: é˜¿é‡Œ Qwen æµ·å¤–ç«™ç‚¹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/qwen-color.png
        - Z.ai:
            href: https://chat.z.ai/
            description: æ™ºè°± GLM æµ·å¤–ç«™ç‚¹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/zai.png
        - è±†åŒ…:
            href: https://www.doubao.com/
            description: è±†åŒ…å¤§è¯­è¨€æ¨¡å‹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/doubao-color.png
        - Kimi:
            href: https://www.kimi.com/
            description: æœˆä¹‹æš—é¢å¼€å‘çš„å¤§è¯­è¨€æ¨¡å‹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/kimi-color.png
        - DeepSeek:
            href: https://chat.deepseek.com/
            description: æ·±åº¦æ±‚ç´¢å¼€å‘çš„å¤§è¯­è¨€æ¨¡å‹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/deepseek-color.png
        - Perplexity:
            href: https://www.perplexity.ai/
            description: Perplexity AI æœç´¢
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/perplexity-color.png
        # - ç§˜å¡”:
        #     href: https://metaso.cn/
        #     description: ç§˜å¡” AI æœç´¢
        #     icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/master/icons/mita.png
        # - è…¾è®¯å…ƒå®:
        #     href: https://yuanbao.tencent.com/
        #     description: è…¾è®¯å®˜æ–¹å¤§è¯­è¨€æ¨¡å‹
        #     icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/yuanbao-color.png
        # - LongCat:
        #     href: https://longcat.chat/
        #     description: ç¾å›¢é¾™çŒ«å¤§æ¨¡å‹
        #     icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/longcat-color.png
        # - Grok é•œåƒ:
        #     href: https://grok.dairoot.cn/admin/
        #     description: ç”± xAI å¼€å‘çš„å¤§è¯­è¨€æ¨¡å‹
        #     icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/grok.png
        # - Copilot:
        #     href: https://copilot.microsoft.com/
        #     description: Microsoft Copilot å®˜æ–¹
        #     icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/githubcopilot.png
        # - æ–‡å¿ƒä¸€è¨€:
        #     href: https://yiyan.baidu.com/
        #     description: ç™¾åº¦å…¬å¸å¼€å‘çš„å¤§è¯­è¨€æ¨¡å‹
        #     icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/wenxin-color.png
        # - å½“è´ AI:
        #     href: https://ai.dangbei.com/
        #     description: å½“è´ AI å¤§æ¨¡å‹èšåˆ
        #     icon: https://simg.doyo.cn/imgfile/bgame/202505/0910003968b3.JPG
        # - You.com:
        #     href: https://you.com/
        #     description: You.com çš„ AI èšåˆç½‘ç«™
        #     icon: https://imgbed.zhubaiwan.me/file/icons/1746104251505_you.com.webp
        # - HuggingfaceChat:
        #     href: https://huggingface.co/chat/
        #     description: Huggingface å¼€æºæ¨¡å‹ä½“éªŒ
        #     icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/huggingface-color.png

        
    - ğŸ› ï¸å¸¸ç”¨å·¥å…·:
        - è®¢é˜…è½¬æ¢:
            href: https://suburl.v1.mk/
            description: è®¢é˜…è½¬æ¢1
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/master/icons/converter.png
        - è®¢é˜…è½¬æ¢ 2:
            href: https://singbox.nyc.mn/
            description: è®¢é˜…è½¬æ¢2
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/master/icons/converter.png
        - å­¦ä¹ é€š:
            href: https://i.chaoxing.com/
            description: è¶…æ–°å­¦ä¹ é€š
            icon: https://imgbed.zhubaiwan.me/file/icons/1744796056894_å­¦ä¹ é€š.png
        - Zlibrary:
            href: https://z-library.sk/
            description: Z-library å›¾ä¹¦ä¸‹è½½
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788117323_z-library.png
        - 4K é«˜æ¸…å£çº¸:
            href: https://haowallpaper.com/
            description: 4K é«˜æ¸…å£çº¸å…è´¹ä¸‹è½½
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788114946_wallpaper.png
        - äºŒæ¬¡å…ƒç”»å»Š:
            href: https://pic.cosine.ren/
            description: æµ·é‡äºŒæ¬¡å…ƒå›¾ç‰‡æ”¶é›†
            icon: https://pic.cosine.ren/favicon.ico
        - Icons:
            href: https://www.iconfont.cn/
            description: é˜¿é‡Œå·´å·´ icons å›¾æ ‡åº“
            icon: https://imgbed.zhubaiwan.me/file/icons/1744795791341_ali-icon.png
        - ç¾å›½åœ°å€ç”Ÿæˆå™¨:
            href: https://www.meiguodizhi.com/
            description: ç”Ÿæˆç¾å›½åœ°å€ä¸è™šæ‹Ÿä¿¡æ¯
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/master/icons/address.png
        - base64 å·¥å…·:
            href: https://www.toolhelper.cn/EncodeDecode/Base64
            description: base64 ç¼–ç è§£ç 
            icon: https://imgbed.zhubaiwan.me/file/icons/1744788096424_base64.png
        - æ²¹çŒ´è„šæœ¬:
            href: https://greasyfork.org/zh-CN
            description: æ²¹çŒ´è„šæœ¬ä¸‹è½½
            icon: https://pic.macked.app/static/2601dfda710c35f87d2673aaf13550bc-1702962186.webp
        # - Cherry Studio:
        #     href: https://www.cherry-ai.com/
        #     description: å¤šå¹³å°çš„ AI å®¢æˆ·ç«¯
        #     icon: https://github.eo.bian666.cf/https://raw.githubusercontent.com/CherryHQ/cherry-studio/main/build/icon.png
        # - å®‰å¨œçš„æ¡£æ¡ˆ:
        #     href: https://zh.annas-archive.org/
        #     description: æœ€å¤§çš„å®Œå…¨å¼€æ”¾çš„å›¾ä¹¦é¦†
        #     icon: https://cdn-1.webcatalog.io/catalog/annas-archive/annas-archive-icon-filled-256.webp
        # - æŠ–éŸ³:
        #     href: https://www.douyin.com/
        #     description: æŠ–éŸ³-è®°å½•ç¾å¥½ç”Ÿæ´»
        #     icon: https://imgbed.zhubaiwan.me/file/icons/1746105423714_æŠ–éŸ³.png
        # - PING0:
        #     href: https://ip.ping0.cc/
        #     description: IP æŸ¥è¯¢æ£€æµ‹
        #     icon: https://imgbed.zhubaiwan.me/file/icons/1744788106820_subscription.png