# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Group 1:
    - ç¾¤ç»„:
        - ç™¾ä¸‡çš„å¤§çª:
            href: https://qm.qq.com/q/F2b0lzn5wm
            description: ç‚¹å‡»å¡ç‰‡åŠ å…¥ç¾¤èŠã€ç™¾ä¸‡çš„å¤§çªã€‘
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/dawo.png
            widget:
                type: calendar
                firstDayInWeek: sunday # optional - defaults to monday
                view: monthly # optional - possible values monthly, agenda
                maxEvents: 10 # optional - defaults to 10
                showTime: true
                timezone: Asia/Shanghai

    - ğŸš€ç™¾ä¸‡å¸¸ç”¨:
        # - HomePage æ–‡æ¡£:
        #     href: https://gethomepage.dev/configs/
        #     description: HomePage å®˜æ–¹æ–‡æ¡£
        #     icon: 
        - å¤§çªé£ä¹¦æ–‡æ¡£:
            href: https://ai.feishu.cn/wiki/E4JfwScP8i58Pbkzmqgcukjanhe
            description: ç™¾ä¸‡çš„å¤§çªç¾¤è§„ä¸åˆ†äº«æ–‡æ¡£
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/feishu.png
        - LinuxDo:
            href: https://linux.do
            description: ä¸€ä¸ªæ–°çš„ç†æƒ³å‹ç¤¾åŒº
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/linuxdo.png
        - ç™¾ä¸‡ API:
            href: https://api.zhubaiwan.xyz/console/log
            description: ç™¾ä¸‡ API ç®¡ç†
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/newapi-color.png
        - Gmail:
            href: https://mail.google.com
            description: Gmail é‚®ç®±ç™»å½•
            icon: https://ssl.gstatic.com/ui/v1/icons/mail/rfr/gmail.ico
        - Bilibili:
            href: https://www.bilibili.com/watchlater/list
            description: B ç«™ç¨åè§‚çœ‹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/bilibili-color.png
        - å®‰ç†å·¥ä¸€å¡é€š:
            href: http://ecard.aust.edu.cn/epay
            description: å®‰å¾½ç†å·¥å¤§å­¦æ ¡å›­å¡å……å€¼
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/AUST.png
        - Gist:
            href: https://gist.github.com/mine
            description: GitHub Gist ä»£ç ç‰‡æ®µ
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/github.png
        - IPLark:
            href: https://iplark.com
            description: IP è´¨é‡æ£€æµ‹
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/iplark.ico
        # - Zone.id:
        #     href: https://my.zone.id/subdomains/2gi4bfiq/url_forwarder/
        #     description: Zone.id å…è´¹åŸŸå
        #     icon: https://my.zone.id/subzoneid.png

    - ğŸŒŸç™¾ä¸‡æ­å»º:
        - PurePage:
            href: https://purepage.baiwan.de
            description: ç™¾ä¸‡çš„åšå®¢
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/purepage.png
        - OuonnkiTV:
            href: https://tv.baiwan.de
            description: ç™¾ä¸‡çš„å…è´¹è§†é¢‘ç½‘ç«™
            icon: https://tv.ouonnki.site/favicon.ico
        - Converter:
            href: https://converter.baiwan.de
            description: Clash è®¢é˜…è½¬æ¢
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/converter.png
        - shadowrocket è´¦å·:
            href: https://apple-id.deno.dev
            description: å…è´¹å°ç«ç®­ Apple è´¦å·
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/shadowrocket.png
        - Model-Get: 
            href: https://model-get.zhubaiwan-oozzxx.me
            description: ç”Ÿæˆ NewAPI æ¨¡å‹æ˜ å°„
            icon: https://img.icons8.com/?size=200&id=POBc2SrrhhnF&format=png
        - BW-model:
            href: https://bw-model.deno.dev
            description: ç™¾ä¸‡ API æ¨¡å‹åˆ—è¡¨
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/dawo.png
        - ç™¾ä¸‡å›¾åºŠ (New):
            href: https://img.baiwan.de
            description: ç™¾ä¸‡çš„å›¾åºŠ (æ–°)
            icon: https://cfbed.sanyue.de/logo.png
        - Cloudflare-Proxy:
            href: https://proxy.baiwan.de
            description: URL ä»£ç†æœåŠ¡
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/proxy.png
        # - Sub-Store:
        #     href: https://sub.zhubaiwan.me
        #     description: ç™¾ä¸‡çš„è®¢é˜…ç®¡ç†
        #     icon: https://gh-proxy.com/https://raw.githubusercontent.com/cc63/ICON/main/Sub-Store.png

- Group 2:
    - â˜ï¸å¼€å‘å·¥å…·/æœåŠ¡:
        - GitHub:
            href: https://github.com
            description: GitHub ä»£ç æ‰˜ç®¡å¹³å°
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/github.png
        - Huggingface:
            href: https://huggingface.co
            description: æœºå™¨å­¦ä¹ ä¸æ•°æ®é›†å¼€æºå¹³å°
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/huggingface-color.png
        - Cloudflare:
            href: https://dash.cloudflare.com
            description: åŸŸåæ‰˜ç®¡ä¸ CDN æœåŠ¡
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/cloudflare-color.png
        - Deno:
            href: https://dash.deno.com
            description: Deno è¿è¡Œæ—¶éƒ¨ç½²å¹³å°
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/deno.png
        - Aliyun:
            href: https://home.console.aliyun.com/home/dashboard/ProductAndService
            description: é˜¿é‡Œäº‘å®˜ç½‘
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/alibabacloud-color.png
        - è…¾è®¯äº‘:
            href: https://cloud.tencent.com
            description: è…¾è®¯äº‘äº‘è®¡ç®—æœåŠ¡å¹³å°
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/tencent-color.png
        - Render:
            href: https://dashboard.render.com
            description: Render äº‘éƒ¨ç½²å¹³å°
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/render.jpg
        - Vercel:
            href: https://vercel.com
            description: Vercel å‰ç«¯éƒ¨ç½²å¹³å°
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/vercel.png
        - Aiven:
            href: https://console.aiven.io
            description: Aiven å…è´¹äº‘æ•°æ®åº“
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/aiven.ico
        - Koofr:
            href: https://app.koofr.net
            description: Koofr äº‘å­˜å‚¨ä¸ WebDAV
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/koofr.png
        # - Zone.id:
        #     href: https://zone.id
        #     description: Zone.id å…è´¹åŸŸå
        #     icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/zoneid.png
        # - Claw Cloud:
        #     href: https://console.run.claw.cloud
        #     description: Claw Cloud åº”ç”¨éƒ¨ç½²å¹³å°
        #     icon: 
        # - Cloudns:
        #     href: https://www.cloudns.net
        #     description: åŸŸåå’Œ DNS æœåŠ¡æä¾›å•†
        #     icon: 

    - ğŸŒˆAI æœåŠ¡:
        - ChatGPT:
            href: https://chatgpt.com
            description: OpenAI å¼€å‘çš„å¤§è¯­è¨€æ¨¡å‹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/openai.png
        - Gemini:
            href: https://gemini.google.com
            description: Google å¼€å‘çš„å¤šæ¨¡æ€å¤§æ¨¡å‹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/gemini-color.png
        - Google AI Studio:
            href: https://aistudio.google.com
            description: ä½¿ç”¨ Gemini API
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/aistudio.png
        - Duck.ai:
            href: https://duck.ai
            description: DuckDuckGo å…è´¹ AI åŠ©æ‰‹
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/duckduckgo.png
        - QwenChat:
            href: https://chat.qwen.ai
            description: é˜¿é‡Œ Qwen æµ·å¤–ç«™ç‚¹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/qwen-color.png
        - Z.ai:
            href: https://chat.z.ai
            description: æ™ºè°± GLM æµ·å¤–ç«™ç‚¹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/zai.png
        - è±†åŒ…:
            href: https://www.doubao.com
            description: è±†åŒ…å¤§è¯­è¨€æ¨¡å‹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/doubao-color.png
        - Kimi:
            href: https://www.kimi.com
            description: æœˆä¹‹æš—é¢å¼€å‘çš„å¤§è¯­è¨€æ¨¡å‹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/kimi-color.png
        - æ–‡å¿ƒä¸€è¨€:
            href: https://ernie.baidu.com
            description: ç™¾åº¦å…¬å¸å¼€å‘çš„å¤§è¯­è¨€æ¨¡å‹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/wenxin-color.png
        - DeepSeek:
            href: https://chat.deepseek.com
            description: æ·±åº¦æ±‚ç´¢å¼€å‘çš„å¤§è¯­è¨€æ¨¡å‹
            icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/deepseek-color.png
        # - Perplexity:
        #     href: https://www.perplexity.ai
        #     description: Perplexity AI æœç´¢
        #     icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/perplexity-color.png
        # - ç§˜å¡”:
        #     href: https://metaso.cn
        #     description: ç§˜å¡” AI æœç´¢
        #     icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/mita.png
        # - è…¾è®¯å…ƒå®:
        #     href: https://yuanbao.tencent.com
        #     description: è…¾è®¯å®˜æ–¹å¤§è¯­è¨€æ¨¡å‹
        #     icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/yuanbao-color.png
        # - LongCat:
        #     href: https://longcat.chat
        #     description: ç¾å›¢é¾™çŒ«å¤§æ¨¡å‹
        #     icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/longcat-color.png
        # - Copilot:
        #     href: https://copilot.microsoft.com
        #     description: Microsoft Copilot å®˜æ–¹
        #     icon: https://registry.npmmirror.com/@lobehub/icons-static-png/latest/files/light/githubcopilot.png
        # - å½“è´ AI:
        #     href: https://ai.dangbei.com
        #     description: å½“è´ AI å¤§æ¨¡å‹èšåˆ
        #     icon: https://simg.doyo.cn/imgfile/bgame/202505/0910003968b3.JPG
        
    - ğŸ› ï¸å¸¸ç”¨å·¥å…·:
        - è®¢é˜…è½¬æ¢:
            href: https://subweb.7li7li.com/
            description: è®¢é˜…è½¬æ¢1
            icon: https://subweb.7li7li.com/favicons/favicon.ico
        - è®¢é˜…è½¬æ¢ 2:
            href: https://singbox.nyc.mn/
            description: è®¢é˜…è½¬æ¢2
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/converter.png
        - å­¦ä¹ é€š:
            href: https://i.chaoxing.com/
            description: è¶…æ–°å­¦ä¹ é€š
            icon: https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/06/8f/80/068f80f1-0a32-9d22-55d7-79e740da32ea/AppIcon-0-0-1x_U007emarketing-0-8-0-85-220.png/200x200ia-75.webp
        - Zlibrary:
            href: https://z-library.sk/
            description: Z-library å›¾ä¹¦ä¸‹è½½
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/z-library.png
        - 4K é«˜æ¸…å£çº¸:
            href: https://haowallpaper.com/
            description: 4K é«˜æ¸…å£çº¸å…è´¹ä¸‹è½½
            icon: https://haowallpaper.com/favicon.ico
        - äºŒæ¬¡å…ƒç”»å»Š:
            href: https://pic.cosine.ren/
            description: æµ·é‡äºŒæ¬¡å…ƒå›¾ç‰‡æ”¶é›†
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/cosine.ico
        - Icons:
            href: https://www.iconfont.cn/
            description: é˜¿é‡Œå·´å·´ icons å›¾æ ‡åº“
            icon: https://img.alicdn.com/imgextra/i4/O1CN01XZe8pH1USpiUNT1QN_!!6000000002517-2-tps-114-114.png
        - ç¾å›½åœ°å€ç”Ÿæˆå™¨:
            href: https://www.meiguodizhi.com/
            description: ç”Ÿæˆç¾å›½åœ°å€ä¸è™šæ‹Ÿä¿¡æ¯
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/address.png
        - base64 å·¥å…·:
            href: https://www.toolhelper.cn/EncodeDecode/Base64
            description: base64 ç¼–ç è§£ç 
            icon: https://www.toolhelper.cn/favicon.ico
        - æ²¹çŒ´è„šæœ¬:
            href: https://greasyfork.org/zh-CN
            description: æ²¹çŒ´è„šæœ¬ä¸‹è½½
            icon: https://gh-proxy.com/https://raw.githubusercontent.com/ZhuBaiwan-oOZZXX/HomePage/main/icons/tampermonkey.png
        # - å®‰å¨œçš„æ¡£æ¡ˆ:
        #     href: https://zh.annas-archive.org/
        #     description: æœ€å¤§çš„å®Œå…¨å¼€æ”¾çš„å›¾ä¹¦é¦†
        #     icon: https://cdn-1.webcatalog.io/catalog/annas-archive/annas-archive-icon-filled-256.webp
        # - æŠ–éŸ³:
        #     href: https://www.douyin.com/
        #     description: æŠ–éŸ³-è®°å½•ç¾å¥½ç”Ÿæ´»
        #     icon: 
        # - PING0:
        #     href: https://ip.ping0.cc/
        #     description: IP æŸ¥è¯¢æ£€æµ‹
        #     icon: 