title: HomePage
description: ç™¾ä¸‡çš„ä¸ªäººä¸»é¡µ
language: zh-CN
favicon: https://imgbed.zhubaiwan.me/file/icons/1744806223771_ç™¾ä¸‡.ico

hideVersion: false
disableUpdateCheck: true

 # è®¾ç½®ç»¿ç‚¹
statusStyle: "dot"
ping: http://127.0.0.1
siteMonitor: http://127.0.0.1

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false
  # google, duckduckgo, bing, baidu, brave or custom
  provider: google 

theme: dark 
color: slate
headerStyle: boxed
 # ç­‰é«˜å¡
useEqualHeights: true

background: 
  image: https://tc-new.z.wiki/autoupload/f/walXAp4Sav94xqwTB9S6BMoKOuqHx97M6G9c8juTwKuyl5f0KlZfm6UsKj-HyTuv/20250810/jZ1V/3840X2160/cover.png
  # ä¸é€æ˜åº¦ï½œå¯ä»¥é€‰æ‹©å€¼ä¸º 0-100
  opacity: 30
  # blur: sm # æ¨¡ç³Šåº¦ï½œsmï¼ˆå°ï¼‰ï½œmdï¼ˆä¸­ç­‰ï¼‰ï½œxlï¼ˆå¤§ï¼‰ï½œ0ï¼ˆæ— æ¨¡ç³Šï¼‰
  # brightness: 100 # äº®åº¦ï½œå¯ä»¥é€‰æ‹©å€¼ä¸º 0ï½œ50ï½œ100
  # saturate: 50 # é¥±å’Œåº¦ï½œå¯ä»¥é€‰æ‹©å€¼ä¸º 0ï½œ50ï½œ100
  # cardBlur: sm # ä¸ºæœåŠ¡å’Œä¹¦ç­¾å¡åº”ç”¨æ¨¡ç³Šæ»¤é•œï½œsmï¼ˆå°ï¼‰ï½œmdï¼ˆä¸­ç­‰ï¼‰ 


layout:
  Group 1:
    style: row
    columns: 3
     # éšè—é¦–é¡µæ ‡é¢˜
    header: false
     # ç­‰é«˜å¡
    useEqualHeights: true
    ç¾¤ç»„:
      style: row
      columns: 1
      header: false
    ğŸš€ç™¾ä¸‡å¸¸ç”¨:
      style: row
      columns: 2
      # ç­‰é«˜å¡
      useEqualHeights: true
    ğŸŒŸç™¾ä¸‡æ­å»º:
      style: row
      columns: 2

  Group 2:
    style: row
    columns: 3
    header: false
    # ç­‰é«˜å¡
    useEqualHeights: true
    â˜ï¸å¼€å‘å·¥å…·/æœåŠ¡:
      style: row
      columns: 2
    ğŸŒˆAI æœåŠ¡:
      style: row
      columns: 2
      # ç­‰é«˜å¡
      useEqualHeights: true
    ğŸ› ï¸å¸¸ç”¨å·¥å…·:
      style: row
      columns: 2