# doc: https://gethomepage.dev/widgets/

# - resources: # ç¡¬ä»¶ä¿¡æ¯
#     cpu: true # CPUä¿¡æ¯
#     memory: true # å†…å­˜ä¿¡æ¯
#     disk: /
#     cputemp: false # CPUæ¸©åº¦
#     uptime: true # ç³»ç»Ÿçš„è¿è¡Œæ—¶é—´ä¿¡æ¯
#     expanded: true # æ˜¾ç¤ºæ‰©å±•è§†å›¾

- openmeteo:
    label: å®‰ç†ğŸ’–
    # ç»åº¦ 
    longitude: 117.0271
    # çº¬åº¦
    latitude: 32.5494
    # æ—¶åŒº
    timezone: Asia/Shanghai
    # ä½¿ç”¨å…¬åˆ¶å•ä½ï¼ˆä¾‹å¦‚ç±³ã€åƒå…‹ã€æ‘„æ°åº¦ç­‰ï¼‰
    units: metric
    # åˆ·æ–°æ—¶é—´ï¼ˆåˆ†é’Ÿï¼‰
    cache: 5

- greeting:
    text_size: xl
    text:  ğŸ’œç™¾ä¸‡çš„ Homepage

- search:
    provider: [google, duckduckgo, bing, baidu, brave]
    focus: false 
    showSearchSuggestions: true
    # One of _self, _blank, _parent or _top
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: medium
      timeStyle: medium
      hourCycle: h23
